export const FETCH_CONTACTS_PENDING = 'FETCH_CONTACTS_PENDING';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_ERROR = 'FETCH_CONTACTS_ERROR';

export const FETCH_GROUPS_PENDING = 'FETCH_GROUPS_PENDING';
export const FETCH_GROUPS_SUCCESS = 'FETCH_GROUPS_SUCCESS';
export const FETCH_GROUPS_ERROR = 'FETCH_GROUPS_ERROR';

export const FETCH_PLANTS_PENDING = 'FETCH_PLANTS_PENDING';
export const FETCH_PLANTS_SUCCESS = 'FETCH_PLANTS_SUCCESS';
export const FETCH_PLANTS_ERROR = 'FETCH_PLANTS_ERROR';

export const FETCH_MESSAGES_PENDING = 'FETCH_MESSAGES_PENDING';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_ERROR = 'FETCH_MESSAGES_ERROR';

export const FETCH_GROUP_MESSAGES_PENDING = 'FETCH_GROUP_MESSAGES_PENDING';
export const FETCH_GROUP_MESSAGES_SUCCESS = 'FETCH_GROUP_MESSAGES_SUCCESS';
export const FETCH_GROUP_MESSAGES_ERROR = 'FETCH_GROUP_MESSAGES_ERROR';

export const FETCH_MESSAGES_COUNT_PENDING = 'FETCH_MESSAGES_COUNT_PENDING';
export const FETCH_MESSAGES_COUNT_SUCCESS = 'FETCH_MESSAGES_COUNT_SUCCESS';
export const FETCH_MESSAGES_COUNT_ERROR = 'FETCH_MESSAGES_COUNT_ERROR';

export const SET_READ_MESSAGE_PENDING = 'SET_READ_MESSAGE_PENDING';
export const SET_READ_MESSAGE_SUCCESS = 'SET_READ_MESSAGE_SUCCESS';
export const SET_READ_MESSAGE_ERROR = 'SET_READ_MESSAGE_ERROR';